name: Documentation Report
description: Report an issue with documentation
labels:
  - needs_triage
  - docs

body:
  - type: markdown
    attributes:
      value: |
        **Thank you reporting an issue with Ansible Builder documentation.**

        If you are looking for community support, please visit
        the [Community guide](https://ansible.readthedocs.io/projects/builder/en/latest/community/)
        for information on how to get in touch.

  - type: textarea
    attributes:
      label: Summary
      description: Describe the problem or suggestion with the documentation
      validations:
        required: true
